### ISSUE TITLE
Remove or fix the invariant be-inv-asserter-person-rel-type

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/allergy#100]
The invariant seems to have an issue in handling the cardinality of relationship. This should be fixed . However, the invariant is too strict - should be demoted. Until then, request quick removal, to unblock testing.

**Comment by HanneVuegen** [comment]
We can remove this constraint since the proper solution is to profile the RelatedPerson to a BeRelatedPerson. On this point the asserter is not mandatory and is not supported by the vaults so this is not blocking.

In relation to this topic I think it would be advisable to open Core workgroups to start discussing RelatedPerson and some changes to ex. BeOrganization, Auditevent (?),...

**Comment by bdc-ehealth** [comment]
@HanneVuegen 

Let's put this on the agenda for the next validation team, with the actual reason for the change.

**Comment by HanneVuegen** [comment]
Hi all,

since the asserter isn't used at the moment by the vaults it can be temporarily removed. I suggest to look into to this more in detail for a next version of the publication.

**Comment by bdc-ehealth** [comment]
@HanneVuegen , @costateixeira ,

As you can see here, there was no issue whatsoever with the examples: https://www.ehealth.fgov.be/standards/fhir/allergy/1.1.0/qa.html . José, could you please point out where the problems are you are referring to in https://github.com/hl7-be/allergy/issues/100#issuecomment-1820900321 ? 

@HanneVuegen ,

I understand the remark Karlien Erauw makes here in a mail from 11/12/2023:

`Wat met issue 100 ivm de Allergy IG (https://github.com/hl7-be/allergy/issues/100), dit lijkt me niet besproken geweest vorige donderdag ?
Ik hoorde van Vlaanderen dat dit de eigenlijk niet nodig is, maar wel de validatie blokkeert en dus ook kritisch is voor de FHIR-a-thon. 
Kunnen we de constraint verwijderen ? Want we kunnen dit nu niet als prioritair aankaarten bij HAPIFHIR.
`
Taking the deadline of the FHIR-a-ton into account, and the improbability that HAPIFHIR will fix this issue in time, we can propose to remove this invariant.
