### ISSUE TITLE
Allergy Intolerance IG URL cannot be found

### ISSUE THREAD

**Issue by pedro-earlytracks** [hl7-be/allergy#115]
The official address posted in the home page of Allergy Intolerance (https://www.ehealth.fgov.be/standards/fhir/allergy/ImplementationGuide/hl7.fhir.be.allergy) doesn't work. 

We need a working URL for the IG to set up a validation tool for resources created using this IG.

**Comment by bdc-ehealth** [comment]
@etasodjo2 ,

for the setup of the validation, this url is enough: https://www.ehealth.fgov.be/standards/fhir/allergy

**Comment by jmp-ehealth** [comment]
@pedro-earlytracks can we close this issue?

**Comment by pedro-earlytracks** [comment]
Hi Jean-Michiel,
Yes, please go ahead.

Kind regards,
Pedro

**Comment by jmp-ehealth** [comment]
Question answered
