### ISSUE TITLE
Allergy Intolerance - Add non-allergic hypersensitivity 

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/allergy#20]
Some discussion here:
https://jira.hl7.org/browse/FHIR-35879

**Comment by JensPenny** [comment]
https://www.hl7.org/fhir/allergyintolerance.html
ch. 9.1.2 looks to be useful as well, this looks kind of in line with the fhir-jira, but the fhir-jira contains more details and other links.

**Comment by costateixeira** [comment]
As decided in previous meetings and from the alignment with FHIR R5-
We will 
* use the Belgian extension for R4
* remove (0..0) the element AllergyIntolerance.type, to avoid double / inconsistent data. This is the same we did for Vaccine.

We will also defer the other issues that are related to this, as they seem to be wanting a confirmation, which is already given.

If the above assumptions are correct, and just as an optional measure of extra safety, we can do this in a few days: 
Propose to validate this decision by the FHIR Validation WorkGroup, and ask the feedback from all participants in the BE Core WG (per mail) for any **blocking** objections. Otherwise the issue is resolved.
