### ISSUE TITLE
recorder is identified by the NISS or NISS bis

### ISSUE THREAD

**Issue by annenerenhausen** [hl7-be/allergy#22]
The recorder is a physical person who takes responsibility for the encoded information. It will therefore be identified by the NISS or NISS bis (mandatory)

But, it is possible to add other information such as the INAMI number, the name and first name, the role, or even the organization. Adding this additional information is optional but highly recommended.

**Comment by bdc-ehealth** [comment]
The WG decides that the NISS is mandatory for the recorder when registering, not for exchanging the information, and that the other information is highly recommended. We will not add this to the current profile.
