### ISSUE TITLE
Add informative text to AllergyIntolerance.recorder on how an Organization can be mentioned

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/allergy#6]
Decision:
Add to the AllergyIntolerance.recorder definition the following text:
...
Since the reference does not support BeOrganization, the BePractitionerRole resource/reference SHALL be used to refer to an organization when needed.

Approved with no abstention on 17-03

**Comment by bdc-ehealth** [comment]
Linked to #8 and #48
