### ISSUE TITLE
Mail by Hanne Vuegen 09/08/2022: Allergyintolerance.asserter

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/allergy#64]
@HanneVuegen

-	the asserter should come from valueset ‘Patientrelationship type’ for relatedperson and not refer to ‘related person’ as long as the Be profile for Related Person doesn’t exist. 
-	and like ‘recorder’ we should always reference the Belgian profiles BePatient, BePractitioner, BePractitionerRole

**Comment by bdc-ehealth** [comment]
treated in #24

**Comment by HanneVuegen** [comment]
ok
