### ISSUE TITLE
Mail by Hanne Vuegen 09/08/2022: Valueset Allergyintolerance.clinicalstatus

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/allergy#67]
@HanneVuegen
-	The definitions don’t match the definitions in the Business rule doc: resolved  pediatric allergies

**Comment by bdc-ehealth** [comment]
Value can be added.

**Comment by HanneVuegen** [comment]
Dag Bart,
zie Business Rules Allergy pagina 18 onderaan: 
[Business Rules Allergy V1.4 NL.docx](https://github.com/hl7-be/allergy/files/9371668/Business.Rules.Allergy.V1.4.NL.docx)


RIZIV heeft contact opgenomen met de Belgische Allergievereniging (BelSACI) voor hun mening en aanbevelingen over de definitie van een inactieve en een opgeloste allergie
ClinicalStatus "opgelost": alleen voor pediatrische allergieën in geval van volledige genezing. Hetzelfde voor intoleranties.
ClinicalStatus "inactief": in geval van langdurige tolerantie na succesvolle desensibilisatiebehandeling.

**Comment by bdc-ehealth** [comment]
I will add this to the description.
