### ISSUE TITLE
Mail by Hanne Vuegen 09/08/2022: Allergyintolerance.verificationstatus

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/allergy#69]
@HanneVuegen

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/eh089/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/eh089/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/eh089/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:36.0pt'>

<p class=MsoNormal style='margin-left:36.0pt;text-indent:-18.0pt;mso-list:l0 level1 lfo1'><![if !supportLists]><span
style='mso-fareast-font-family:Calibri'><span style='mso-list:Ignore'>-<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]><span style='mso-fareast-font-family:"Times New Roman"'>Can
we add rules for:<o:p></o:p></span></p>

Beschrijving | Rol | VerificationStatus
-- | -- | --
Ingave van de gegevens door de   patiënt | Patiënt | Unconfirmed
Arts ontvangt positief   testresultaat* | Arts | Confirmed
Arts ontvangt negatief   testresultaat* | Arts | Refuted
Patiënt vertelt zorgverlener   dat hij/zij allergisch is | Zorgverlener KB 78   (specificeer) | Unconfirmed

</body>

</html>

**Comment by bdc-ehealth** [comment]
Invariants can be added, but will be too complex. They will depend on the practitioner role, or on the analysis of the RIZIV/INAMI number. We can add it as documentation though.

**Comment by HanneVuegen** [comment]
What do you mean by adding it as documentation?

**Comment by bdc-ehealth** [comment]
We can add your table to the guidance.xml.
