### ISSUE TITLE
add the value Non-allergic hypersensitivity into the value set Type of the FHIR profile Allergy

### ISSUE THREAD

**Issue by annenerenhausen** [hl7-be/allergy#81]
La problématique  des différents types de classifications d’allergie a été exposée lors du congrès HL7 International le 21 septembre à Baltimore, la décision du groupe a été de changer le type  vers un CodeableConcept, et laisser le binding strength « preferred ». Cela nous permet finalement d’utiliser un value set avec les types « Allergy », « Non-allergic hypersensitivity » et « Intolerance ». 

Techniquement, ce changement sera dans la nouvelle version FHIR R5 (Mid-2023), mais il peut être adopté immédiatement via une extension puisque FHIR permet/préconise d’importer des éléments de la R5 comme extensions, en évitant une extension belge.

**Comment by bdc-ehealth** [comment]
Sadly, it is not as simple as this: 

```
Bonjour Bart,
 
Anne va prendre contact avec José pour avoir une explication/discussion avec lui. Nous verrons ensuite comment avancer.
 
Bonne journée,
 
Mike 

```

**Comment by bdc-ehealth** [comment]
During the meeting of 27/10 (FHIR validation meeting), it was agreed by José that a solution without a Belgian extension is not possible until after the release of R5. (As opposed to the original message from José to Anne: https://github.com/hl7-be/allergy/issues/81#issue-1403247846).

**Comment by bdc-ehealth** [comment]
see source #84

**Comment by bdc-ehealth** [comment]
Code 609433001 | Hypersensitivity disposition (finding) | was missing from previous commit #83

**Comment by costateixeira** [comment]
This is the same as #20.
