### ISSUE TITLE
Invariant be-inv-asserter-person-rel-type - what if empty?

### ISSUE THREAD

**Issue by smals-bvv** [hl7-be/allergy#87]
Hi,

When connecting to the newest version of the Implementation Guide for AllergyIntolerance using the NPMValidationSupport feature of HAPI, we notice an inconsistency in the profile definition.
As the cardinality of the field asserter is 0..1 we can conclude this is an optional property.
However the invariant be-inv-asserter-person-rel-type (defined in the list of constraints) is returning an error in case asserter is empty.
Is this behavior expected or can the invariant be extended with the following statement: ‘or asserter.empty()’ or should the cardinality of asserter change to 1..1?

Link to AllergyIntolerance.asserter:
https://www.ehealth.fgov.be/standards/fhir/allergy/StructureDefinition-be-allergyintolerance-definitions.html#AllergyIntolerance.asserter 
Link to constraints:
https://www.ehealth.fgov.be/standards/fhir/allergy/StructureDefinition-be-allergyintolerance.html#constraints

Kind regards,
Brecht Van Vooren
Vitalink-FHIR

**Comment by bdc-ehealth** [comment]
@smals-bvv 

Indeed, according to https://build.fhir.org/ig/HL7/FHIRPath/#implies this will result in an error. This is a technical error that will be immediately fixed and published with the upcoming new publication.
