### ISSUE TITLE
Fix type valueset binding to extensible

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/allergy#91]
The reason HL7 Intl left it as preferred is because there were 2 codes before, and their meaning obviously does not map 1:1 to the 3 codes we'd want or other sets of codes. 
Since we want to enforce these codes to be used, like in the rest of the spec, this should be extensible.

Note: preapplied in the release candidate.

**Comment by bdc-ehealth** [comment]
@costateixeira Taking into account the attitude of Isabelle Pollet, I'd prefer to present this change to a WG.
