### ISSUE TITLE
Added value or reason for identifier with coding system https://www.ehealth.fgov.be/standards/fhir/allergy/NamingSystem/be-ns-allergy

### ISSUE THREAD

**Issue by nicovn** [hl7-be/allergy#98]
What is the added value, or reason for requiring an identifier with coding system https://www.ehealth.fgov.be/standards/fhir/allergy/NamingSystem/be-ns-allergy in the AllergyIntolerance resource ?

Where does that identifier come from ?

Can you give an example ?

**Comment by bdc-ehealth** [comment]
@nicovn ,

the reason for this identifier is that the business wants to be able to link copies in different systems together. So if a system, e.g. RSW has an allergy registration, (with its own technical id), and it passes it on to Vitalink (with its own technical id, i.e. a different one from the RSW id), than it can still know it is about the same allergy registration.

**Comment by nicovn** [comment]
Hi Bart,

And who will generate those identifiers in naming system https://www.ehealth.fgov.be/standards/fhir/allergy/NamingSystem/be-ns-allergy ?

Will eHealth foresee a service/endpoint that Vitalink/RSW, hospital EPR vendors... can call to generate a unique id in that naming system ?

Sorry, but I don't see how this will work in real world ...

Thanks !

Nico
